[supervisord]
nodaemon=true

[program:backend]
command=python -m uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
directory=/app/backend
autostart=true
autorestart=true
stdout_logfile=/app/backend.log
stderr_logfile=/app/backend_err.log

[program:frontend]
command=python -m http.server 3000
directory=/app/frontend
autostart=true
autorestart=true
stdout_logfile=/app/frontend.log
stderr_logfile=/app/frontend_err.log
